api_id: 2060693 # This has to be an integer. Read more [here](https://core.telegram.org/api/obtaining_api_id)
api_hash: '4f3a5f5ad52bc9ebd9090b27feb43276' # Long 32 characters hash identifier. Read more [here](https://core.telegram.org/api/obtaining_api_id)
session_name: 'carbonforward' # Session name. Only one session (with a unique session name) can run at a time

# The channel names that you'd like to forward messages from.
# The user running the client must have these channels present on it's dialogs.
input_channel_names:
  -'test' 
  

# The output channel names that the messages will be forwarded to.
# The user running the client must have a write access to those channels, and have the channels present on theirs dialogs.
output_channel_names: 
  -'test'
